#ifndef NMBS_CONFIG_H
#define NMBS_CONFIG_H

// ---- Modo de operación ----
#define NMBS_CLIENT_DISABLED

// ---- Funciones desactivadas ----
#define NMBS_SERVER_READ_DEVICE_IDENTIFICATION_DISABLED
#define NMBS_SERVER_WRITE_FILE_RECORD_DISABLED
#define NMBS_SERVER_READ_FILE_RECORD_DISABLED
#define NMBS_SERVER_WRITE_MULTIPLE_COILS_DISABLED
#define NMBS_READ_COILS_DISABLED
#define NMBS_READ_DISCRETE_INPUTS_DISABLED
#define NMBS_WRITE_SINGLE_COIL_DISABLED
#define NMBS_WRITE_MULTIPLE_REGISTERS_DISABLED

// ---- Tamaños ----
#define NMBS_MSG_BUF_SIZE 32

#endif